### ISSUE TITLE
Timestamping of the Pointcloud in ROS

### ISSUE THREAD

**Issue by Patrick-Lascombe** [RoboSense-LiDAR/rslidar_sdk#10]
Hello, 
With the paramerter use_lidar_clock = true, the timestamping of the ROS sensor_msgs::PointCloud2 message. The call to get the lidar clock is executed on the first packed of the scan or the last packet of the scan ?

Thank you for your help

**Comment by CrazyTomX** [comment]
Hi,
The timestamp of the point cloud is the time of the **last** packet of the scan.

**Comment by Patrick-Lascombe** [comment]
Thanks, and also thank you for the 1.3.0 release the ring and timestamp info are really valuables !

**Comment by RonaldEnsing** [comment]
Note that other sensors (such as Ouster) use the **first** packet of the scan, while the RoboSense is using the **last** packet of the scan for time stamping the point cloud. This can give some confusion. Autoware specifies the following:

> The header of the point cloud message is expected to have the time of the earliest point it has.
