### ISSUE TITLE
Feature Request: Organized Point Cloud

### ISSUE THREAD

**Issue by TillBeemelmanns** [RoboSense-LiDAR/rslidar_sdk#11]
ROS's [PointCloud2.msg](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/PointCloud2.html) message format supports an organized 2d (image-like) point cloud format. For some applications it might be beneficial to work with such an organized point cloud, where the point cloud are organized according to their ring and their firing cycle / azimuth.  

Best Regads

**Comment by CrazyTomX** [comment]
Hi,
 For now, the output point cloud of rslidar_sdk is already saved in order. By default its the column major order and you can adjust it to row major order by modifying parameter.
