### ISSUE TITLE
Timestamping per point

### ISSUE THREAD

**Issue by Patrick-Lascombe** [RoboSense-LiDAR/rslidar_sdk#12]
Hello,

When digging into the driver and the timestamping per point, I noticed that in reality it is a timestamping per datablock instead of a timestamping per point.
Is it planned to have one day a true timestamping per point ?

Thanks for your help

**Comment by CrazyTomX** [comment]
Hi,
For now, we set points in one column with a same timestamp (not one block) because the resolution is high enough. For a 10hz LiDAR, there are 1800 columns in one frame so the time resolution is 100ms/1800=0.055ms. 
For now, there is no plan to keep increasing the time resolution for each point.

**Comment by Patrick-Lascombe** [comment]
Thank you for the answer

**Comment by hazemy** [comment]
Per-point timestamp is supported. Change the CMakeLists.txt as described [here](https://github.com/RoboSense-LiDAR/rslidar_sdk/blob/main/doc/howto/05_how_to_change_point_type.md).
