### ISSUE TITLE
PTP Time Syncronization

### ISSUE THREAD

**Issue by TwiggyDaniels** [RoboSense-LiDAR/rslidar_sdk#138]
Just wanted to verify something, should be a quick answer.

We are synchronizing our devices using PTP with a RS Ruby Plus 128. I wanted to verify that PTP would override the sensor's internal clock and so by setting `use_lidar_time: true` LiDAR data collected would be synchronized PTP time?

**Comment by boxanm** [comment]
I'm also curious about this topic. @TwiggyDaniels did you find the answer yourself?

**Comment by HaoQChen** [comment]
yes, just set use_lidar_time: true to find if PTP works well
