### ISSUE TITLE
Not receiving any messages with error: ERRCODE_MSOPTIMEOUT

### ISSUE THREAD

**Issue by maxpolzin** [RoboSense-LiDAR/rslidar_sdk#139]
We have a BPearl Lidar (IP 192.168.1.200) and it is connecting to a freshly installed Ubuntu 22.04 host running ROS2 Humble. Wireshark sees UDP packages on the ports 6699 and 7788. The ROS2 drivers compile just fine, though when starting at a rate of 1Hz this error is shown:

`
ERRCODE_MSOPTIMEOUT 
`

Do you have any ideas how to resolve it? Thank you for your help in advance.

I am attaching screenshots to show the configurations in detail.

![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/20051567/79402695-7091-4454-9813-e9b0ce78499f)
![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/20051567/78fc77d7-aef0-444c-ac9e-7962d85e29a2)
![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/20051567/9e5f987a-8302-46b7-b92b-66d5d8316d3e)
![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/20051567/a7adb254-fe71-4f67-b5ca-0400daf0a193)
![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/20051567/92a4d16e-b20b-4587-8f84-3662a09a0671)

**Comment by JTShuai** [comment]
Do you allow the ports to pass the firewall?

**Comment by maxpolzin** [comment]
I receive the packages in Wireshark. If I record a PCAP file in Wireshark,
I can also visualize it in the viewer.

Thus, I conclude the firewall is not the problem, but rather the SDK that
trys to decode/receive the packages.

How should I check if the firewall is nevertheless an issue? Are you
talking about the Linux firewall, ufw?

JTShuai ***@***.***> schrieb am Fr., 3. Mai 2024, 10:16:

**Comment by nawfalz** [comment]
I had the same issue. I managed to resolve it by running the following commands:
$ sudo ufw allow 6699/udp
$ sudo ufw allow 7788/udp

**Comment by maxpolzin** [comment]
@JTShuai and @nawfalz: Thank you for your inputs.

Enabling the ports in the firewall has resolved the issue! 

What was puzzling me to this point was able to receive and record packages with Wireshark. I didn't understand how Wireshark and the Firewall interplayed.

**Comment by JTShuai** [comment]
> @JTShuai and @nawfalz: Thank you for your inputs.
> 
> Enabling the ports in the firewall has resolved the issue!
> 
> What was puzzling me to this point was able to receive and record packages with Wireshark. I didn't understand how Wireshark and the Firewall interplayed.

 Wireshark operates "before" firewall and sees all the packets that the network card receives. Then the packets get filtered by the firewall.

For more information, please check the link: https://ask.wireshark.org/question/31184/wireshark-capture-packets-after-or-before-firewall/
