### ISSUE TITLE
Bpearl Driver Initializing error only on RSView

### ISSUE THREAD

**Issue by Abdob** [RoboSense-LiDAR/rslidar_sdk#145]
We are following the Bpearl User Guide Version 1.1 November 2023

We installed the latest RSView for Ubuntu 20 (Version 4.3.11): Downloads - RoboSense | World Leader in LiDAR and Perception Solutions

We are able to publish Lidar Data is ROS however when attempting to visualize the data using RSVIEW we get the error:
setsockopt: : Invalid argument
Driver Initialize Error...

Please see below for current firmware and initialization details.

Note: this was attempted after system restart when no other application is using the MSOP/DIFOP ports. We noticed our firmware was out of date and are requesting one compatible with the given RSView Version.
![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/8084476/74d00638-97fb-43a7-8949-a7f7573e1741)

wave@wave82:~/Downloads/RSVIEW/RSView_ubu20_v4.3.11$ ./run_rsview.sh
paraview version 4.3.1
finish initialization!
------------------------------------------------------
             RoboSense Driver Parameters
input type: ONLINE_LIDAR
lidar_type: RSBP
frame_id: rslidar
------------------------------------------------------
------------------------------------------------------
             RoboSense Input Parameters
msop_port: 6699
difop_port: 7788
host_address: 192.168.1.102
group_address: 192.168.1.200
pcap_path:
pcap_rate: 1
pcap_repeat: 1
use_vlan: 0
user_layer_bytes: 0
tail_layer_bytes: 0
------------------------------------------------------
------------------------------------------------------
             RoboSense Decoder Parameters
wait_for_difop: 0
min_distance: 0.1
max_distance: 300
start_angle: 0
end_angle: 360
use_lidar_clock: 1
dense_points: 0
config_from_file: 0
angle_path:
split_frame_mode: 1
split_angle: 0
num_blks_split: 1
------------------------------------------------------
------------------------------------------------------
             RoboSense Transform Parameters
valid: 0
x: 0
y: 0
z: 0
roll: 0
pitch: 0
yaw: 0
------------------------------------------------------
setsockopt: : Invalid argument
Driver Initialize Error...

**Comment by FelixHuang18** [comment]
hello, group_address refers to the multicast address, which should be set to 0.0.0.0 in your case.
