### ISSUE TITLE
Catkin_make error pcap.h

### ISSUE THREAD

**Issue by gtirth** [RoboSense-LiDAR/rslidar_sdk#147]
Hello,

I have tried to build the rslidar_sdk package on nuc13 by following README.md but I am getting following error.
![image](https://github.com/RoboSense-LiDAR/rslidar_sdk/assets/109450810/30a5667d-76fa-44ce-bacd-041a08e38b36)

Any insights would be appreciated!!

Thanks

**Comment by gtirth** [comment]
Resolved

**Comment by ShareefUMN** [comment]
Dealing with the same error. could you share the fix?

**Comment by Huuaiyuan** [comment]
> Dealing with the same error. could you share the fix?

sudo apt-get install libpcap-dev libeigen3-dev libboost-dev libpcl-dev
