### ISSUE TITLE
dense pointcloud

### ISSUE THREAD

**Issue by yzzymt** [RoboSense-LiDAR/rslidar_sdk#16]
Hi,
Can we get dense pointcloud directly from 1.3 sdk by changing some config parameters?
When I work with rslidar 16, I need remove NaN from the pointcloud first.

**Comment by HaoQChen** [comment]
according to `pcl/point_cloud.h`

`is_dense - specifies if all the data in points is finite (true), or whether it might contain Inf/NaN values (false). ` 

when some condition occur, point will be set to NAN in `driver/decoder/decoder_RS16.hpp/decodeMsopPkt`:

![image](https://user-images.githubusercontent.com/13584792/103257637-f5260e00-49cc-11eb-96a4-61837c2e8e80.png)

maybe you can change NAN to 0.0001 and set `pcl_pointcloud->is_dense` to true in your `pointCloudCallback`

**Comment by yzzymt** [comment]
I see, thank you so much for your quick response
