### ISSUE TITLE
Regarding custom IP and MSOP DIFOP on M1B3

### ISSUE THREAD

**Issue by yzhou377** [RoboSense-LiDAR/rslidar_sdk#17]
Hi!

I was trying to connect multiple M1B3 on my device, but I could not find and resources to set custom IP, MSOP, and DIFOP to avoid device confusion. I noticed that for Ruby and other devices, I can do this in RSVIEW. However, there are no tools for M1B3 at the moment. 

I am running the platform on ROS1 with Ubuntu 16.04, can someone help? Thanks!

**Comment by HaoQChen** [comment]
Please contact armin.mu@robosense.cn. My colleague will help you with that

**Comment by HaoQChen** [comment]
Hi, Can this issue be closed?

**Comment by haolei523** [comment]
Did the modification work?
