### ISSUE TITLE
Build fails due to PointCloudLibrary needing C++14

### ISSUE THREAD

**Issue by duncanmcbryde** [RoboSense-LiDAR/rslidar_sdk#2]
Following a fresh install on Ubuntu 20.04 on ROS Noetic. The build failed with both cmake and catkin_make. It appears that PointCloudLibrary requires C++14, but C++11 is set by default. I have created this bug to associate it with the pull request generated here:
https://github.com/RoboSense-LiDAR/rslidar_sdk/pull/1

**Comment by CrazyTomX** [comment]
Thanks for ur advice! We will take the advice and update add_definitions(-std=c++11) in CmakeLists to add_definitions(-std=c++14). That will solve the compiling problems in ubuntu 16.04, 18.04 & 20.04.  The new version will be released in September.
