### ISSUE TITLE
how to convert RS_Ruby cloud to range image?

### ISSUE THREAD

**Issue by YangSiri** [RoboSense-LiDAR/rslidar_sdk#36]
Hi, 

Could you please tell me how to convert 128 RS_Ruby point cloud into range image? What's the actual horizontal angle resolution?

Looking forward to your help ;)

**Comment by HaoQChen** [comment]
umm, we haven't tried this so far

horizontal angle resolution is 0.2 degree

you could find some information about pinhole model of camera

**Comment by YangSiri** [comment]
Thanks, @HaoQChen

**Comment by FishInWave** [comment]
> 谢谢，@HaoQchen
> 
> 当我使用预定义的点云格式**RsPointXYZIRT**并 通过**pcl::fromROSMsg(*laserCloudRsPointXYZIRT)**将其从 ros msg 转换为点云 时的另一个问题**；**，出现以下错误。你能告诉我哪里可能出错吗？
> 
> ![图片](https://user-images.githubusercontent.com/33154113/118125302-5fde6000-b429-11eb-8a18-953d16b355ed.png)

Have you solved this problem?
