### ISSUE TITLE
Lidar frequency parameters (RS_BPearl)

### ISSUE THREAD

**Issue by Patrick-Lascombe** [RoboSense-LiDAR/rslidar_sdk#4]
Hello, 

I didn't saw a parameter to change the LIDAR frequency in the config.yaml file. It also did not appear in the hidden parameters. Is there a way to change the frequency from the driver or do I need to set it with another method ?

Thank you for your time

**Comment by CrazyTomX** [comment]
I'm gonna to close this issue and please feel free to comment if you have any more questions.
