### ISSUE TITLE
Multilidar Time Synchronization

### ISSUE THREAD

**Issue by sif95** [RoboSense-LiDAR/rslidar_sdk#46]
I am trying to connect multiple lidars to synchronize with the same GPS time. Is it possible to synchronize multiple lidar with the same timestamp?

**Comment by tbroed** [comment]
Did you find an answer to this question?

**Comment by mjseppa** [comment]
We are running PPS to couple RS-16s, then use use_lidar_clock. Atleast RS-16 has FW bug where it triggers on falling edge so we had to add 1.1s time offset with 100ms PPS pulse.

**Comment by RS-Alex** [comment]
> I am trying to connect multiple lidars to synchronize with the same GPS time. Is it possible to synchronize multiple lidar with the same timestamp?

Robosense can offer a sync board that allows multiple lidars to run with the same GPS signal. Please contact your sales manager for more information.
