### ISSUE TITLE
UCWP packet port number

### ISSUE THREAD

**Issue by Patrick-Lascombe** [RoboSense-LiDAR/rslidar_sdk#5]
Hello,

I would want to send an UCWP packet to modify the lidar configuration while the driver is launched.
I tried to find the port number for the UCWP connection but it was not listed in the documentation. 

Is it possible to know which port it is ?

Thanks

**Comment by CrazyTomX** [comment]
Hi, the UCWP should be same as the MSOP port.

**Comment by Patrick-Lascombe** [comment]
Perfect, thank you!

**Comment by abust005** [comment]
> Perfect, thank you!

@Patrick-Lascombe Can you confirm that this is the case? I've been scanning network traffic with Wireshark and haven't seen any configuration packets from RSView with destination port same as MSOP, but the configuration from RSView still works.
