### ISSUE TITLE
Compile with ROS catkin tools

### ISSUE THREAD

**Issue by ManChrys** [RoboSense-LiDAR/rslidar_sdk#53]
Hello,

in the instructions on step 2 says to rename package_ros1.xml to package.xml but when im catkin_make i have the following errors:

-- ROS Found, Ros Support is turned On!
=============================================================
CMake Error: File /media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/catkin_ws/src/rslidar_sdk/package_ros1.xml does not exist.
CMake Error at rslidar_sdk/CMakeLists.txt:34 (configure_file):
  configure_file Problem configuring file

**edit**

as i was looking inside the CmakeList i found this on line 34

  `configure_file(${CMAKE_CURRENT_SOURCE_DIR}/package_ros1.xml ${CMAKE_CURRENT_SOURCE_DIR}/package.xml COPYONLY) `

so i have to copy and rename the file and not just rename it right?

**Comment by baoxianzhang** [comment]
configure_file need package_ros1.xml, so for now you don't need to copy and rename the file, the configure_file will do it for you.  
But configure_file does't work when use catkin_make directly, we consider to remove the configure_file function.

**Comment by ManChrys** [comment]
@baoxianzhang thank you my friend.
