### ISSUE TITLE
20.04?

### ISSUE THREAD

**Issue by LukeAI** [RoboSense-LiDAR/rslidar_sdk#55]
Is 20.04 supported yet?
Is there likely to be another release in the near future?

**Comment by phmatin1962** [comment]
Hi, I did install the sdk with 20.04 with ros noetic.
 I did follow the procedure written at  : https://github.com/RoboSense-LiDAR/rslidar_sdk
** using Git
git clone https://github.com/RoboSense-LiDAR/rslidar_sdk.git
cd rslidar_sdk
git submodule init
git submodule update
** then YAML
sudo apt-get update
sudo apt-get install -y libyaml-cpp-dev
** then PCAP
sudo apt-get install -y  libpcap-dev
** then protobuf
sudo apt-get install -y libprotobuf-dev protobuf-compiler
** then compile: Copy first the sdk under your catkin env/src, then go up
**Copy  the file package_ros1.xml en package.xml
** edit the file CMakeLists.txt an change the compilation option to
#=======================================
# Compile setup (ORIGINAL,CATKIN,COLCON)
#=======================================
set(COMPILE_METHOD CATKIN)
**then compile 
catkin_make (at the good place)
** Configure for your Lidar
** edit the file catkin_ws/src/rslidar_sdk/config/config.yaml
** change the   ** change     lidar_type: RS16            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
** change       frame_id: rslidar           #Frame id of message (note that / will be suppress before rslidar: this is a pb for 20.04)

**execute
source devel/setup.bash
roslaunch rslidar_sdk start.launch
** connect the sensor and visualize oin RVIZ windows

ps : for roslaunch maybe you can need to source the setup.bash of your ros distribution

Hope this help

Philippe
