### ISSUE TITLE
Pb when using the sdk on 20.04LTS

### ISSUE THREAD

**Issue by phmatin1962** [RoboSense-LiDAR/rslidar_sdk#56]
I tried to use the sdk on 20.04LTS Following the Readme file. Compilation was ok. Lauching was no error
When using either RS16 or RS80  Rviz shows 
Global status : Warn
Fixed frame: No TF data
Point cloud (forbbiden symbol)
==>Status: Error
Any idea?

**Comment by phmatin1962** [comment]
After contacting ROBOSENSE, just it is required to change the name of frame_id by suppressing the / before rslidar
	         frame_id: rslidar           #Frame id of message

**Comment by gitouni** [comment]
I tried the repo in the env of "Ubuntu20.04 ROS2-foxy" and found that v1.3.0 could not be compiled successfully (fortunately v1.2.2 is ok).
