### ISSUE TITLE
RS32 point cloud looks flat

### ISSUE THREAD

**Issue by NozomiWyane** [RoboSense-LiDAR/rslidar_sdk#68]
![image](https://user-images.githubusercontent.com/34018545/145018934-8dfe99ff-30f1-40a4-8c68-77f147ba6523.png)
this is how it looks like when I run sdk in ubuntu ros.
![image](https://user-images.githubusercontent.com/34018545/145019088-5443e835-3efd-49e2-8995-19e668dc5b5e.png)
The config is list below.
![image](https://user-images.githubusercontent.com/34018545/145019180-f3ef0b95-e2d1-456a-9bd8-bd144796e3e3.png)
Please help me out.

**Comment by RS-Alex** [comment]
[angle.csv](https://github.com/RoboSense-LiDAR/rslidar_sdk/files/7673947/angle.csv)
Please add the angle path parameter in your config file. You can find the detailed information about "angle path" parameter in driver "hidden_parameter_intro" file.
The angle.csv file is attached

**Comment by NozomiWyane** [comment]
> 

Thanks for your support. I try this csv in my path then the point cloud change to this below.
![image](https://user-images.githubusercontent.com/34018545/145165903-9e1317e8-75b3-44e9-981e-a25e6785d138.png)

My config.yaml is list below:
`common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
                                                        #4: packet message comes from Protobuf-UDP
                                                        #5: point cloud comes from Protobuf-UDP
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
  send_packet_proto: false                              #true: Send packets through Protobuf-UDP
  send_point_cloud_proto: false                         #true: Send point cloud through Protobuf-UDP
  pcap_path: /home/robosense/lidar.pcap                 #The path of pcap file

lidar:
  - driver:
      lidar_type: RS32            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /rslidar           #Frame id of message
      msop_port: 6699              #Msop port of lidar
      difop_port: 7788             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
      angle_path: /home/cdp/ws_lidar/src/rslidar_sdk/config/angle.csv
      split_frame_mode: 1
      cut_angle: 0
      num_pkts_split: 1
      wait_for_difop: true
      saved_by_rows: false
      multi_cast_address: 0.0.0.0
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
    ros:
      ros_recv_packet_topic: /rslidar_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to
`
I think it still doesn't work normally. Please help?

**Comment by RS-Alex** [comment]
Can I ask if you were playing with the RS-Helios (New 32 beam) or RS-32 (old 32 beam) unit?
Can I please have your SN number?

**Comment by NozomiWyane** [comment]
Im using the old 32 beam and SN is161181401417

**Comment by RS-Alex** [comment]
It seems like this lidar is faulty, please try run this lidar in the RS-View software and if the performance is still the same, please contact our sales manager for fix/replacement issue.

**Comment by NozomiWyane** [comment]
There is no points in the RSview. But I can still see points in ros sdk. Is there something wrong in my config of RSview?
![image](https://user-images.githubusercontent.com/34018545/145178449-f4895bed-5b6b-44c3-8317-e8039904a82d.png)
Three csv files are also in this dir

**Comment by RS-Alex** [comment]
Please select RSlidar32. You also need to make sure your port is set correctly. (Tools -> data port setting)
![image](https://user-images.githubusercontent.com/95340476/145179706-2ab59daa-07ab-4d3f-80f8-77b9ca890e8c.png)

**Comment by NozomiWyane** [comment]
![image](https://user-images.githubusercontent.com/34018545/145180571-279868c5-99c1-49b9-836d-4ca81b8c2bf0.png)
Now points cloud looks like this.
I found a fault diagnosis and result like this
![image](https://user-images.githubusercontent.com/34018545/145180687-dd952a0e-61b7-4109-969b-8e90a283ae04.png)

**Comment by RS-Alex** [comment]
Please contact our sales manager for fix/replacement issues.
