### ISSUE TITLE
Align license with `rslidar_msg`

### ISSUE THREAD

**Issue by Timple** [RoboSense-LiDAR/rslidar_sdk#73]
The license of the package `rslidar_msg` is not in line with this package. In fact it is missing.

Little developers seem to be subscribed to the `rslidar_msg`, but I've opened up a pull-request to fix this:
https://github.com/RoboSense-LiDAR/rslidar_msg/pull/1

**Comment by RS-Alex** [comment]
Thanks for the feedback, we will add the license shortly

**Comment by ronzheng1006** [comment]
We have merge this PR. Thanks.

**Comment by Timple** [comment]
Thank you!
