### ISSUE TITLE
Multiple LiDAR launch from single workspace.

### ISSUE THREAD

**Issue by ajay1606** [RoboSense-LiDAR/rslidar_sdk#74]
Hello ,

We are currently using 3 Lidars (Ruby, 2 BPearl), is there any way that I can modify the ROS rslidar_sdk_node to launch 3 Lidars from the same computer.

APpreciate your response.

Regards,
Ajay

**Comment by RS-Alex** [comment]
Yes you can use multiple lidars on the same computer.
You can find the instructions in SDK. Path below:
\src\rslidar_sdk\doc\howto\how_to_use_multi_lidars.md

**Comment by ajay1606** [comment]
@RS-Alex Thanks Alex for your quick response. But there is an issue with configuring BPearl Port Number to launch multiple LiDARS. As I understood that, BPearl Models doesn't support for the web interface, I have tried with the RSView downloaded from the following link; [link](https://www.robosense.ai/en/resources-20)
After the following instructions am getting the following warning notification and am unable to set a unique port number for each lidar. I have tried with 4 units of BPearl LiDARS (Purchased recently). All 4 units have the same problem.

We greatly appreciate your kind assistance as we are looking to fix this as soon as possible. Ref screenshot attached.

Sensor Configuration Tab:
![image](https://user-images.githubusercontent.com/29722843/150743900-fff374ea-3b70-4619-a8a6-5fcda9e57435.png)

After clicking the **Get** button (There were no sensor information loading), Also Tried with selecting BP option from Drop menu.
![image](https://user-images.githubusercontent.com/29722843/150744023-bcd1ae54-ea99-4e6c-a972-3e5a7ea4bb0e.png)

Again after trying with **set LiDAR**
![image](https://user-images.githubusercontent.com/29722843/150744211-5dee89f6-8610-4f38-903b-4caa2213e8c2.png)

There was no configuration saved. Greatly appreciate your response.

Regards,
Ajay

**Comment by RS-Alex** [comment]
Hi Ajay
Before parameter settings please check the version of your BPearl:
![image](https://user-images.githubusercontent.com/95340476/150746245-8b2ccdd1-5b49-4283-b78b-d8116fc7f421.png)
You can only set lidar by RSView if the revision is 2.1.0. If the revision is 3.0, you need to go to browser webpage and put in lidar IP to change all the parameters.
If the revision version is ok, and you are still having problem connecting lidars, please contact alex.guo@robosense.cn, we can make online meeting for further diagnose.

**Comment by ajay1606** [comment]
@RS-Alex Thanks for your quick response. All 4 units were V2.1.0 versions. And figured out the reason for that cause. 
After verifying the data in Wireshark, it is understood that there is a mismatch with **difop_port** and **msop_port** numbers. After fixing that correctly as it mentioned in Wireshark, Get and SetLiDAR options working well.

Many thanks for your quick responses and continued support.  

Regards,
Ajay

**Comment by RS-Alex** [comment]
No problem, please contact if you have any more questions:)
