### ISSUE TITLE
Can LidarPointCloudMsg convert to PointCloudMsg?

### ISSUE THREAD

**Issue by MCTENV** [RoboSense-LiDAR/rslidar_sdk#8]
robosense::lidar::LidarPointCloudMsg怎么转成robosense::lidar::PointCloudMsg？
前者是sdk中的消息格式，后者是demo中的消息格式，在msg中只有lidarPointCloudMsg转成ROS消息的函数，而没有pointCloudMsg转ROS消息的函数？

**Comment by CrazyTomX** [comment]
1， 由于内核中点云脱离PCL， PointCloudMsg中的点云定义其实就是一个std::vector.  因为在日常使用中主要用法都是将内核点云转换成外层PCL的点云进行使用，所以并未提供反向转换的函数。 如果有需要，可以参rslidar_sdk/src/adapter/driver_adapter.hpp
中的转换函数，逆向转换即可。 PCL的底层实现也是std::vector,所以本质上这两种消息的转换就是vector的复制。

2， 由于PCL提供了转ROS消息的函数，所以在sdk中是先将内核的脱离pcl的点云转换成了pcl点云，然后在使用ros发送时，调用的pcl官方的转换函数转成ROS消息发出。

**Comment by MCTENV** [comment]
好的，非常感谢您的解答，我已经实现了。
