### ISSUE TITLE
Update CMakeLists.txt

### ISSUE THREAD

**Issue by adamanov** [RoboSense-LiDAR/rslidar_sdk#84]
Update please CMakeLists.txt or  [Step 4.1](https://github.com/RoboSense-LiDAR/rslidar_sdk#41-compile-directly) in readme.
By default right now in repo [CMakeLists](https://github.com/RoboSense-LiDAR/rslidar_sdk/blob/34ac46b398add4e86c81d4a19d764f24afd8054d/CMakeLists.txt#L8) `set(COMPILE_METHOD CATKIN)` is setted. To use `./rslidar_sdk_node` it is needed to complied with `set(COMPILE_METHOD ORIGINAL)` . Otherwise `./rslidar_sdk_node`  will not be generated inside `build` folder (it will be located somewhere in subfolders and lead to conflict)

**Comment by Timple** [comment]
Hi @adamanov, would you mind trying the branch from PR #48?

I'm curious if that would solve your issue.

**Comment by adamanov** [comment]
> Hi @adamanov, would you mind trying the branch from PR #48?
> 
> I'm curious if that would solve your issue.


Hello Timple, I don't have any problem right now,  I solved it by compiling with `set(COMPILE_METHOD ORIGINAL)` it works fine. 

However, I tried also your repo with branch `ros12` . It is still not generating ./rslidar_sdk_node 

```
cd rslidar_sdk
mkdir build && cd build
cmake .. && make -j4
./rslidar_sdk_node   # <---- is not generated 
```

see my terminal

```
[100%] Built target rslidar_sdk_node
adamanov@GL62M-7RDX:~/rslidar_sdk/build$ ls
atomic_configure  catkin_generated  CMakeCache.txt  cmake_install.cmake     CTestCustom.cmake    devel  Makefile  test_results
catkin            CATKIN_IGNORE     CMakeFiles      CTestConfiguration.ini  CTestTestfile.cmake  gtest  src
adamanov@GL62M-7RDX:~/rslidar_sdk/build$ ./rslidar_sdk_node
bash: ./rslidar_sdk_node: No such file or directory
adamanov@GL62M-7RDX:~/rslidar_sdk/build$ ls
atomic_configure  catkin_generated  CMakeCache.txt  cmake_install.cmake     CTestCustom.cmake    devel  Makefile  test_results
catkin            CATKIN_IGNORE     CMakeFiles      CTestConfiguration.ini  CTestTestfile.cmake  gtest  src
adamanov@GL62M-7RDX:~/rslidar_sdk/build$ cd devel/lib/
pkgconfig/   rslidar_sdk/ 
adamanov@GL62M-7RDX:~/rslidar_sdk/build$ cd devel/lib/rslidar_sdk/
adamanov@GL62M-7RDX:~/rslidar_sdk/build/devel/lib/rslidar_sdk$ ls
rslidar_sdk_node
adamanov@GL62M-7RDX:~/rslidar_sdk/build/devel/lib/rslidar_sdk$ ./rslidar_sdk_node 
********************************************************
**********                                    **********
**********    RSLidar_SDK Version: v1.3.2     **********
**********                                    **********
********************************************************
[ERROR] [1647606392.391811506]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...
[ INFO] [1647606397.577108725]: Connected to master at [localhost:11311]
[rospack] Error: package 'rslidar_sdk' not found
[librospack]: error while executing command
Config file format wrong! Please check the format(e.g. indentation) 
adamanov@GL62M-7RDX:~/rslidar_sdk/build/devel/lib/rslidar_sdk$ 
```

**Comment by Cloudytosunny** [comment]
> > Hi @adamanov, would you mind trying the branch from PR #48?
> > I'm curious if that would solve your issue.
> 
> Hello Timple, I don't have any problem right now, I solved it by compiling with `set(COMPILE_METHOD ORIGINAL)` it works fine.
> 
> However, I tried also your repo with branch `ros12` . It is still not generating ./rslidar_sdk_node
> 
> ```
> cd rslidar_sdk
> mkdir build && cd build
> cmake .. && make -j4
> ./rslidar_sdk_node   # <---- is not generated 
> ```
> 
> see my terminal
> 
> ```
> adamanov@GL62M-7RDX:~/rslidar_sdk$ git branch -a
> * release
>   remotes/origin/HEAD -> origin/release
>   remotes/origin/config-param
>   remotes/origin/release
>   remotes/origin/revert-42-release
>   remotes/origin/ros12
>   remotes/origin/ros12-config-param
>   remotes/origin/ros12-dev
>   remotes/origin/yaml-cpp
> adamanov@GL62M-7RDX:~/rslidar_sdk$ git checkout ros12
> Branch 'ros12' set up to track remote branch 'ros12' from 'origin'.
> Switched to a new branch 'ros12'
> adamanov@GL62M-7RDX:~/rslidar_sdk$ git branch -a
>   release
> * ros12
>   remotes/origin/HEAD -> origin/release
>   remotes/origin/config-param
>   remotes/origin/release
>   remotes/origin/revert-42-release
>   remotes/origin/ros12
>   remotes/origin/ros12-config-param
>   remotes/origin/ros12-dev
>   remotes/origin/yaml-cpp
> adamanov@GL62M-7RDX:~/rslidar_sdk$ git submodule init
> Submodule 'src/rs_driver' (https://github.com/RoboSense-LiDAR/rs_driver.git) registered for path 'src/rs_driver'
> adamanov@GL62M-7RDX:~/rslidar_sdk$ git submodule update
> Cloning into '/home/adamanov/rslidar_sdk/src/rs_driver'...
> Submodule path 'src/rs_driver': checked out 'de731dc0ad254da72bad4bd70c8e648dfc098bf0'
> adamanov@GL62M-7RDX:~/rslidar_sdk$ mkdir build && cd build
> adamanov@GL62M-7RDX:~/rslidar_sdk/build$ cmake .. && make -j4
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> =============================================================
> -- ROS Found, Ros Support is turned On!
> =============================================================
> =============================================================
> -- ROS2 Not Found, Ros2 Support is turned Off!
> =============================================================
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> =============================================================
> -- Protobuf Found, Protobuf Support is turned On!
> =============================================================
> -- COMPILING /home/adamanov/rslidar_sdk/src/msg/proto_msg/packet.proto USING /usr/bin/protoc
> -- COMPILING /home/adamanov/rslidar_sdk/src/msg/proto_msg/point_cloud.proto USING /usr/bin/protoc
> -- COMPILING /home/adamanov/rslidar_sdk/src/msg/proto_msg/scan.proto USING /usr/bin/protoc
> -- Checking for module 'eigen3'
> --   Found eigen3, version 3.4.0
> -- Found eigen: /usr/local/include/eigen3  
> -- Checking for module 'libopenni'
> --   Found libopenni, version 1.5.4.0
> -- Found openni: /usr/lib/libOpenNI.so  
> -- The imported target "vtkRenderingPythonTkWidgets" references the file
>    "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
> but this file does not exist.  Possible reasons include:
> * The file was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and contained
>    "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
> but not all the files it references.
> 
> -- The imported target "vtk" references the file
>    "/usr/bin/vtk"
> but this file does not exist.  Possible reasons include:
> * The file was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and contained
>    "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
> but not all the files it references.
> 
> -- Found libusb-1.0: /usr/include  
> -- Checking for module 'flann'
> --   Found flann, version 1.9.1
> -- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a  
> -- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so  
> -- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so  
> -- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so  
> -- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so  
> -- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so  
> -- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so  
> -- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so  
> -- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so  
> -- Found PCL_2D: /usr/include/pcl-1.8  
> -- Found PCL_GEOMETRY: /usr/include/pcl-1.8  
> -- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so  
> -- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so  
> -- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so  
> -- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so  
> -- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so  
> -- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so  
> -- Found PCL_KEYPOINTS: /usr/lib/x86_64-linux-gnu/libpcl_keypoints.so  
> -- Found PCL_TRACKING: /usr/lib/x86_64-linux-gnu/libpcl_tracking.so  
> -- Found PCL_RECOGNITION: /usr/lib/x86_64-linux-gnu/libpcl_recognition.so  
> -- Found PCL_STEREO: /usr/lib/x86_64-linux-gnu/libpcl_stereo.so  
> -- Found PCL_APPS: /usr/lib/x86_64-linux-gnu/libpcl_apps.so  
> -- Found PCL_IN_HAND_SCANNER: /usr/include/pcl-1.8  
> -- Found PCL_MODELER: /usr/include/pcl-1.8  
> -- Found PCL_POINT_CLOUD_EDITOR: /usr/include/pcl-1.8  
> -- Found PCL_OUTOFCORE: /usr/lib/x86_64-linux-gnu/libpcl_outofcore.so  
> -- Found PCL_PEOPLE: /usr/lib/x86_64-linux-gnu/libpcl_people.so  
> -- Using CATKIN_DEVEL_PREFIX: /home/adamanov/rslidar_sdk/build/devel
> -- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
> -- This workspace overlays: /opt/ros/melodic
> -- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
> -- Using PYTHON_EXECUTABLE: /usr/bin/python2
> -- Using Debian Python package layout
> -- Using empy: /usr/bin/empy
> -- Using CATKIN_ENABLE_TESTING: ON
> -- Call enable_testing()
> -- Using CATKIN_TEST_RESULTS_DIR: /home/adamanov/rslidar_sdk/build/test_results
> -- Found gtest sources under '/usr/src/googletest': gtests will be built
> -- Found gmock sources under '/usr/src/googletest': gmock will be built
> -- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
> -- Using Python nosetests: /usr/bin/nosetests-2.7
> -- catkin 0.7.29
> -- BUILD_SHARED_LIBS is on
> -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
> =============================================================
> -- Cmake run for UNIX GNU Compiler
> =============================================================
> -- Boost version: 1.65.1
> -- Found the following Boost libraries:
> --   system
> --   date_time
> --   regex
> =============================================================
> -- rs_driver Version : v1.3.2
> =============================================================
> =============================================================
> -- POINT_TYPE is XYZI
> =============================================================
> -- Configuring done
> CMake Warning at CMakeLists.txt:141 (add_executable):
>   Cannot generate a safe runtime search path for target rslidar_sdk_node
>   because files in some directories may conflict with libraries in implicit
>   directories:
> 
>     runtime library [libboost_filesystem.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_regex.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_system.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_thread.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_chrono.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_date_time.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_atomic.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
>     runtime library [libboost_program_options.so.1.65.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/lib
> 
>   Some of these libraries may not be found correctly.
> 
> 
> -- Generating done
> -- Build files have been written to: /home/adamanov/rslidar_sdk/build
> Scanning dependencies of target rslidar_sdk_node
> [ 16%] Building CXX object CMakeFiles/rslidar_sdk_node.dir/node/rslidar_sdk_node.cpp.o
> [ 33%] Building CXX object CMakeFiles/rslidar_sdk_node.dir/src/msg/proto_msg/packet.pb.cc.o
> [ 50%] Building CXX object CMakeFiles/rslidar_sdk_node.dir/src/msg/proto_msg/scan.pb.cc.o
> [ 66%] Building CXX object CMakeFiles/rslidar_sdk_node.dir/src/manager/adapter_manager.cpp.o
> [ 83%] Building CXX object CMakeFiles/rslidar_sdk_node.dir/src/msg/proto_msg/point_cloud.pb.cc.o
> [100%] Linking CXX executable devel/lib/rslidar_sdk/rslidar_sdk_node
> [100%] Built target rslidar_sdk_node
> adamanov@GL62M-7RDX:~/rslidar_sdk/build$ ls
> atomic_configure  catkin_generated  CMakeCache.txt  cmake_install.cmake     CTestCustom.cmake    devel  Makefile  test_results
> catkin            CATKIN_IGNORE     CMakeFiles      CTestConfiguration.ini  CTestTestfile.cmake  gtest  src
> adamanov@GL62M-7RDX:~/rslidar_sdk/build$ ./rslidar_sdk_node
> bash: ./rslidar_sdk_node: No such file or directory
> adamanov@GL62M-7RDX:~/rslidar_sdk/build$ ls
> atomic_configure  catkin_generated  CMakeCache.txt  cmake_install.cmake     CTestCustom.cmake    devel  Makefile  test_results
> catkin            CATKIN_IGNORE     CMakeFiles      CTestConfiguration.ini  CTestTestfile.cmake  gtest  src
> adamanov@GL62M-7RDX:~/rslidar_sdk/build$ cd devel/lib/
> pkgconfig/   rslidar_sdk/ 
> adamanov@GL62M-7RDX:~/rslidar_sdk/build$ cd devel/lib/rslidar_sdk/
> adamanov@GL62M-7RDX:~/rslidar_sdk/build/devel/lib/rslidar_sdk$ ls
> rslidar_sdk_node
> adamanov@GL62M-7RDX:~/rslidar_sdk/build/devel/lib/rslidar_sdk$ ./rslidar_sdk_node 
> ********************************************************
> **********                                    **********
> **********    RSLidar_SDK Version: v1.3.2     **********
> **********                                    **********
> ********************************************************
> [ERROR] [1647606392.391811506]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...
> [ INFO] [1647606397.577108725]: Connected to master at [localhost:11311]
> [rospack] Error: package 'rslidar_sdk' not found
> [librospack]: error while executing command
> Config file format wrong! Please check the format(e.g. indentation) 
> adamanov@GL62M-7RDX:~/rslidar_sdk/build/devel/lib/rslidar_sdk$ cd ..
> ```

Can you run your ros master?
